/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LoginComponent {
    }
    interface RegisterComponent {
    }
}
declare global {
    interface HTMLLoginComponentElement extends Components.LoginComponent, HTMLStencilElement {
    }
    var HTMLLoginComponentElement: {
        prototype: HTMLLoginComponentElement;
        new (): HTMLLoginComponentElement;
    };
    interface HTMLRegisterComponentElement extends Components.RegisterComponent, HTMLStencilElement {
    }
    var HTMLRegisterComponentElement: {
        prototype: HTMLRegisterComponentElement;
        new (): HTMLRegisterComponentElement;
    };
    interface HTMLElementTagNameMap {
        "login-component": HTMLLoginComponentElement;
        "register-component": HTMLRegisterComponentElement;
    }
}
declare namespace LocalJSX {
    interface LoginComponent {
    }
    interface RegisterComponent {
    }
    interface IntrinsicElements {
        "login-component": LoginComponent;
        "register-component": RegisterComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "login-component": LocalJSX.LoginComponent & JSXBase.HTMLAttributes<HTMLLoginComponentElement>;
            "register-component": LocalJSX.RegisterComponent & JSXBase.HTMLAttributes<HTMLRegisterComponentElement>;
        }
    }
}
